export const NAV = [
  { key: 'dashboard', icon: 'layout-grid', label: 'Dashboard' },
  { key: 'cronograma', icon: 'calendar', label: 'Cronograma' },
  { key: 'questoes', icon: 'book-open', label: 'Questões' },
  { key: 'simulados', icon: 'timer', label: 'Simulados' },
  { key: 'revisoes', icon: 'repeat', label: 'Revisões' },
  { key: 'desempenho', icon: 'trending-up', label: 'Desempenho' },
  { key: 'estatisticas', icon: 'chart-column', label: 'Estatísticas' },
  { key: 'favoritos', icon: 'star', label: 'Favoritos' },
  { key: 'disciplinas', icon: 'library', label: 'Disciplinas' },
  { key: 'anotacoes', icon: 'notebook-pen', label: 'Anotações' },
  { key: 'configuracoes', icon: 'settings', label: 'Configurações' },
];

export const PAGE_META = {
  dashboard: { title: 'Olá, Maria! 💜', sub: 'Vamos continuar rumo à aprovação na OAB?' },
  cronograma: { title: 'Cronograma', sub: 'Seu plano de estudos organizado especialmente para você.' },
  questoes: { title: 'Questões', sub: 'Pratique questões filtradas por disciplina, banca e dificuldade.' },
  simulados: { title: 'Simulados', sub: 'Treine em condições reais de prova.' },
  revisoes: { title: 'Revisões', sub: 'Sua revisão inteligente para fixar o que realmente importa.' },
  desempenho: { title: 'Desempenho', sub: 'Acompanhe sua evolução ao longo do tempo.' },
  estatisticas: { title: 'Estatísticas', sub: 'Números detalhados do seu estudo.' },
  favoritos: { title: 'Favoritos', sub: 'Questões que você marcou como favoritas.' },
  disciplinas: { title: 'Disciplinas', sub: 'Organize seu estudo por matéria.' },
  anotacoes: { title: 'Anotações', sub: 'Organize seus resumos, mapas mentais e ideias.' },
  configuracoes: { title: 'Configurações', sub: 'Preferências da sua conta.' },
};

export const DISCIPLINAS = [
  { nome: 'Direito Constitucional', pct: 85, horas: '35h 20m', cor: '#8B5CF6' },
  { nome: 'Direito Administrativo', pct: 72, horas: '28h 10m', cor: '#EC4899' },
  { nome: 'Direito Civil', pct: 68, horas: '20h 30m', cor: '#06B6D4' },
  { nome: 'Direito Penal', pct: 65, horas: '18h 40m', cor: '#F59E0B' },
  { nome: 'Direito do Trabalho', pct: 60, horas: '14h 05m', cor: '#10B981' },
  { nome: 'Direito Tributário', pct: 35, horas: '9h 15m', cor: '#EF4444' },
  { nome: 'Direito Empresarial', pct: 40, horas: '8h 50m', cor: '#6366F1' },
  { nome: 'Direito Internacional', pct: 45, horas: '7h 30m', cor: '#0EA5E9' },
];

export const QUESTOES = [
  { id: 1, disciplina: 'Direito Constitucional', topico: 'Direitos Fundamentais', subtopico: 'Direito à vida', dificuldade: 'Fácil', banca: 'FGV', ano: 2023, enunciado: 'De acordo com a CF/88, os direitos fundamentais:', alternativas: ['São absolutos e não admitem restrição.', 'Podem ser objeto de cláusula pétrea.', 'Aplicam-se apenas a brasileiros natos.', 'Excluem os estrangeiros residentes.'], correta: 1, explicacao: 'Os direitos fundamentais podem ser objeto de cláusula pétrea conforme CF/88, Art. 60, § 4º.', errosComuns: [{ alternativa: 0, motivo: 'Confunde direitos absolutos com direitos fundamentais.' }], referencias: ['CF/88 Art. 5º', 'CF/88 Art. 60 § 4º'], fonte: 'mock' },
  { id: 2, disciplina: 'Direito Administrativo', topico: 'Princípios da Administração Pública', subtopico: 'Princípio da Legalidade', dificuldade: 'Fácil', banca: 'CEBRASPE', ano: 2022, enunciado: 'A administração pública direta e indireta obedecerá ao princípio da:', alternativas: ['Discricionariedade plena', 'Legalidade', 'Autotutela irrestrita', 'Hierarquia absoluta'], correta: 1, explicacao: 'O princípio da legalidade é fundamental na administração pública, exigindo atuação conforme a lei.', errosComuns: [{ alternativa: 0, motivo: 'Administração pública não tem discricionariedade plena.' }], referencias: ['CF/88 Art. 37', 'Lei 9.784/99'], fonte: 'mock' },
  { id: 3, disciplina: 'Direito Penal', topico: 'Teoria Geral do Crime', subtopico: 'Crimes contra patrimônio', dificuldade: 'Média', banca: 'FGV', ano: 2023, enunciado: 'Quanto ao crime de furto, é correto afirmar que:', alternativas: ['Admite tentativa', 'É crime unissubsistente', 'Não admite qualificadoras', 'Exige violência à pessoa'], correta: 0, explicacao: 'O furto admite tentativa, pois é crime plurissubsistente.', errosComuns: [{ alternativa: 3, motivo: 'Furto é apropriação de coisa alheia sem violência (é roubo que exige violência).' }], referencias: ['CP Art. 155', 'CP Art. 157'], fonte: 'mock' },
  { id: 4, disciplina: 'Direito Civil', topico: 'Parte Geral', subtopico: 'Pessoas Naturais', dificuldade: 'Fácil', banca: 'CEBRASPE', ano: 2022, enunciado: 'Nos termos do Código Civil, a personalidade civil da pessoa começa:', alternativas: ['Na concepção', 'Do nascimento com vida', 'Aos 16 anos', 'Com o registro civil'], correta: 1, explicacao: 'A personalidade civil começa do nascimento com vida, conforme CC Art. 2º.', errosComuns: [{ alternativa: 0, motivo: 'A lei protege direitos da pessoa nascida, mas a personalidade só surge com o nascimento com vida.' }], referencias: ['CC Art. 2º', 'CC Art. 1º'], fonte: 'mock' },
  { id: 5, disciplina: 'Direito Constitucional', topico: 'Separação dos Poderes', subtopico: 'Poder Executivo', dificuldade: 'Média', banca: 'FGV', ano: 2021, enunciado: 'São atribuições privativamente do Presidente da República:', alternativas: ['Fazer leis complementares', 'Vetar projetos de lei', 'Julgar crimes contra a honra', 'Legislar sobre orçamento'], correta: 1, explicacao: 'O veto é atribuição privativa do Executivo, conforme CF/88 Art. 66.', errosComuns: [{ alternativa: 0, motivo: 'Leis complementares são feitas pelo Congresso, não pelo Presidente.' }], referencias: ['CF/88 Art. 66'], fonte: 'mock' },
  { id: 6, disciplina: 'Direito Administrativo', topico: 'Atos Administrativos', subtopico: 'Elementos do ato', dificuldade: 'Difícil', banca: 'CEBRASPE', ano: 2023, enunciado: 'Um ato administrativo é nulo quando:', alternativas: ['Causar prejuízo ao erário', 'Violar a lei', 'O servidor discordar da decisão', 'Não for registrado por escrito'], correta: 1, explicacao: 'A nulidade do ato ocorre por violação à lei, conforme CC Art. 166.', errosComuns: [{ alternativa: 0, motivo: 'Prejuízo ao erário gera improbidade, não nulidade automática.' }], referencias: ['Lei 9.784/99 Art. 2º'], fonte: 'mock' },
  { id: 7, disciplina: 'Direito Penal', topico: 'Penas', subtopico: 'Aplicação das penas', dificuldade: 'Difícil', banca: 'FGV', ano: 2022, enunciado: 'A pena de multa deve ser fixada:', alternativas: ['Sem limite máximo', 'Em dias-multa ou em unidade monetária fixa', 'Apenas em dias-multa', 'De forma arbitrária pelo juiz'], correta: 1, explicacao: 'A pena de multa pode ser fixada em dias-multa ou unidade monetária, conforme CP Art. 49.', errosComuns: [{ alternativa: 0, motivo: 'A lei estabelece limites máximos para a multa.' }], referencias: ['CP Art. 49', 'CP Art. 50'], fonte: 'mock' },
  { id: 8, disciplina: 'Direito Civil', topico: 'Obrigações', subtopico: 'Inadimplemento', dificuldade: 'Média', banca: 'CEBRASPE', ano: 2023, enunciado: 'A mora é caracterizada por:', alternativas: ['Destruição da coisa devida', 'Atraso na execução da obrigação', 'Recusa expressa da obrigação', 'Transferência da obrigação'], correta: 1, explicacao: 'Mora é o atraso injustificado na execução da obrigação, conforme CC Art. 397.', errosComuns: [{ alternativa: 2, motivo: 'Recusa é inadimplemento absoluto, não mora.' }], referencias: ['CC Art. 397', 'CC Art. 398'], fonte: 'mock' },
  { id: 9, disciplina: 'Direito Constitucional', topico: 'Controle de Constitucionalidade', subtopico: 'Ações constitucionais', dificuldade: 'Média', banca: 'FGV', ano: 2023, enunciado: 'A ação declaratória de inconstitucionalidade compete:', alternativas: ['Ao juiz de primeira instância', 'Ao Supremo Tribunal Federal', 'Ao Tribunal de Apelação', 'Ao Ministério Público'], correta: 1, explicacao: 'A ADI compete originariamente ao STF, conforme CF/88 Art. 102, I, a.', errosComuns: [{ alternativa: 0, motivo: 'O controle concentrado é competência do STF.' }], referencias: ['CF/88 Art. 102, I, a', 'Lei 9.868/99'], fonte: 'mock' },
  { id: 10, disciplina: 'Direito Administrativo', topico: 'Serviços Públicos', subtopico: 'Concessão e Permissão', dificuldade: 'Fácil', banca: 'CEBRASPE', ano: 2022, enunciado: 'A concessão de serviço público é:', alternativas: ['Sempre gratuita', 'Um contrato mediante remuneração', 'Exclusivamente para entidades privadas', 'Ato de disposição patrimonial'], correta: 1, explicacao: 'A concessão é contrato entre poder público e concessionário para exploração de serviço público.', errosComuns: [{ alternativa: 0, motivo: 'A concessão envolve remuneração pelo serviço.' }], referencias: ['Lei 8.987/95', 'Lei 9.074/95'], fonte: 'mock' },
  { id: 11, disciplina: 'Direito Civil', topico: 'Contratos', subtopico: 'Vício do consentimento', dificuldade: 'Média', banca: 'FGV', ano: 2023, enunciado: 'O dolo contratual é:', alternativas: ['Ignorância quanto aos fatos', 'Artifício para provocar erro em outrem', 'Culpa na execução', 'Omissão de informação'], correta: 1, explicacao: 'Dolo é o artifício empregado para induzir alguém em erro, conforme CC Art. 147.', errosComuns: [{ alternativa: 3, motivo: 'Omissão simples não é dolo, exige artifício ativo.' }], referencias: ['CC Art. 147', 'CC Art. 148'], fonte: 'mock' },
  { id: 12, disciplina: 'Direito Penal', topico: 'Crimes contra pessoa', subtopico: 'Homicídio', dificuldade: 'Fácil', banca: 'CEBRASPE', ano: 2022, enunciado: 'O homicídio qualificado é punido com pena de:', alternativas: ['5 a 10 anos', '12 a 30 anos', '15 a 40 anos', '10 a 20 anos'], correta: 2, explicacao: 'Homicídio qualificado: pena de 12 a 30 anos, conforme CP Art. 121, § 2º.', errosComuns: [{ alternativa: 3, motivo: 'Pena de 10 a 20 anos é para homicídio simples.' }], referencias: ['CP Art. 121'], fonte: 'mock' },
  { id: 13, disciplina: 'Direito Constitucional', topico: 'Direitos Políticos', subtopico: 'Voto e participação política', dificuldade: 'Fácil', banca: 'FGV', ano: 2022, enunciado: 'O direito ao voto é:', alternativas: ['Obrigatório em todas as eleições', 'Facultativo para maiores de 18 anos', 'Restrito a brasileiros natos', 'Transferível'], correta: 1, explicacao: 'O voto é direito e dever, obrigatório para maiores de 18 anos, conforme CF/88 Art. 14.', errosComuns: [{ alternativa: 2, motivo: 'Brasileiros naturalizados também têm direito ao voto em eleições.' }], referencias: ['CF/88 Art. 14', 'Lei 4.737/65'], fonte: 'mock' },
  { id: 14, disciplina: 'Direito Administrativo', topico: 'Responsabilidade da Administração', subtopico: 'Responsabilidade extracontratual', dificuldade: 'Média', banca: 'CEBRASPE', ano: 2023, enunciado: 'A responsabilidade objetiva da administração pública significa:', alternativas: ['Não há direito à indenização', 'Indeniza-se sem necessidade de culpa comprovada', 'O agente responde pessoalmente', 'Necessário provar negligência'], correta: 1, explicacao: 'Responsabilidade objetiva não exige comprovação de culpa, apenas do dano e nexo causal.', errosComuns: [{ alternativa: 2, motivo: 'A administração responde objetivamente, não o agente pessoalmente.' }], referencias: ['CF/88 Art. 37, § 6º', 'CC Art. 43'], fonte: 'mock' },
  { id: 15, disciplina: 'Direito Civil', topico: 'Família', subtopico: 'Casamento', dificuldade: 'Fácil', banca: 'FGV', ano: 2023, enunciado: 'O casamento é:', alternativas: ['Sempre comunitário', 'Indissolúvel', 'Ato jurídico criador de direitos e deveres', 'Válido sem manifestação de vontade'], correta: 2, explicacao: 'Casamento é ato jurídico que cria direitos e deveres entre os cônjuges.', errosComuns: [{ alternativa: 1, motivo: 'O casamento pode ser dissolvido por divórcio.' }], referencias: ['CC Art. 1.511'], fonte: 'mock' },
  { id: 16, disciplina: 'Direito Penal', topico: 'Crimes contra patrimônio', subtopico: 'Roubo', dificuldade: 'Média', banca: 'FGV', ano: 2022, enunciado: 'Roubo é distinto de furto porque:', alternativas: ['Não admite tentativa', 'Envolve violência ou grave ameaça', 'Só se aplica a valores elevados', 'Requer premeditation'], correta: 1, explicacao: 'Roubo envolve violência ou ameaça, diferentemente do furto, conforme CP Art. 157.', errosComuns: [{ alternativa: 2, motivo: 'Não há limite mínimo de valor para caracterizar roubo.' }], referencias: ['CP Art. 157', 'CP Art. 155'], fonte: 'mock' },
  { id: 17, disciplina: 'Direito Constitucional', topico: 'Direitos Sociais', subtopico: 'Direito ao trabalho', dificuldade: 'Fácil', banca: 'CEBRASPE', ano: 2023, enunciado: 'O direito ao trabalho é garantido pela Constituição como:', alternativas: ['Direito absoluto sem restrições', 'Direito social garantido a todos', 'Exclusivo de brasileiros natos', 'Opcional para maiores de idade'], correta: 1, explicacao: 'O direito ao trabalho é direito social garantido a todos, conforme CF/88 Art. 6º.', errosComuns: [{ alternativa: 0, motivo: 'O direito ao trabalho não é absoluto, está sujeito a regulação legal.' }], referencias: ['CF/88 Art. 6º', 'CF/88 Art. 5º'], fonte: 'mock' },
  { id: 18, disciplina: 'Direito Administrativo', topico: 'Contratos Administrativos', subtopico: 'Características', dificuldade: 'Média', banca: 'FGV', ano: 2023, enunciado: 'Os contratos administrativos se distinguem dos contratos privados por:', alternativas: ['Terem sempre duração indeterminada', 'Serem sempre escritos', 'Possuírem características de ato administrativo', 'Não poderem ser rescindidos'], correta: 2, explicacao: 'Contratos administrativos possuem características de atos administrativos.', errosComuns: [{ alternativa: 1, motivo: 'Contratos administrativos podem ser verbais em alguns casos.' }], referencias: ['Lei 8.666/93', 'Lei 14.133/21'], fonte: 'mock' },
  { id: 19, disciplina: 'Direito Civil', topico: 'Responsabilidade Civil', subtopico: 'Dano moral', dificuldade: 'Média', banca: 'CEBRASPE', ano: 2022, enunciado: 'Dano moral é caracterizado por:', alternativas: ['Apenas dano econômico', 'Violação dos direitos da personalidade', 'Culpa comprovada do agente', 'Lucro cessante apenas'], correta: 1, explicacao: 'Dano moral é violação dos direitos da personalidade, gerando indenização.', errosComuns: [{ alternativa: 0, motivo: 'Dano moral é dano extrapatrimonial, não econômico.' }], referencias: ['CC Art. 186', 'CC Art. 927'], fonte: 'mock' },
  { id: 20, disciplina: 'Direito Penal', topico: 'Prescrição', subtopico: 'Prescrição da pretensão punitiva', dificuldade: 'Difícil', banca: 'FGV', ano: 2023, enunciado: 'A prescrição da pretensão punitiva se interrompe por:', alternativas: ['Trânsito em julgado da sentença', 'Recebimento da denúncia', 'Ato que nega a existência do crime', 'Fato do ofendido'], correta: 1, explicacao: 'O recebimento da denúncia interrompe a prescrição, conforme CP Art. 117, II.', errosComuns: [{ alternativa: 0, motivo: 'Trânsito em julgado marca o fim da ação penal, não interrupção.' }], referencias: ['CP Art. 117', 'CP Art. 100'], fonte: 'mock' },
  { id: 21, disciplina: 'Direito Constitucional', topico: 'Cláusulas Pétreas', subtopico: 'Limitações ao poder constituinte', dificuldade: 'Difícil', banca: 'CEBRASPE', ano: 2022, enunciado: 'As cláusulas pétreas são:', alternativas: ['Fáceis de modificar', 'Imodificáveis por emenda constitucional', 'Válidas apenas na primeira constituição', 'Suspensas em estado de sítio'], correta: 1, explicacao: 'Cláusulas pétreas são imodificáveis, protegem núcleo duro da Constituição, conforme CF/88 Art. 60, § 4º.', errosComuns: [{ alternativa: 0, motivo: 'Cláusulas pétreas justamente não podem ser facilmente modificadas.' }], referencias: ['CF/88 Art. 60, § 4º'], fonte: 'mock' },
  { id: 22, disciplina: 'Direito Administrativo', topico: 'Poderes Administrativos', subtopico: 'Poder vinculado e discricionário', dificuldade: 'Fácil', banca: 'FGV', ano: 2022, enunciado: 'Ato administrativo vinculado é aquele em que:', alternativas: ['O servidor tem liberdade total', 'A lei deixa margem à vontade do servidor', 'A lei especifica exatamente como proceder', 'O servidor pode decidir conforme sua moral'], correta: 2, explicacao: 'Ato vinculado é aquele em que a lei especifica precisamente como deve proceder.', errosComuns: [{ alternativa: 1, motivo: 'Margem de vontade é característica do ato discricionário.' }], referencias: ['Lei 9.784/99 Art. 2º'], fonte: 'mock' },
  { id: 23, disciplina: 'Direito Civil', topico: 'Sucessões', subtopico: 'Ordem de vocação hereditária', dificuldade: 'Média', banca: 'CEBRASPE', ano: 2023, enunciado: 'Na ordem de vocação hereditária, quem vem em primeiro lugar:', alternativas: ['Os ascendentes', 'Os cônjuges', 'Os descendentes', 'Os colaterais'], correta: 2, explicacao: 'Os descendentes vêm em primeiro lugar na ordem de vocação hereditária, conforme CC Art. 1.829.', errosComuns: [{ alternativa: 1, motivo: 'O cônjuge concorre com descendentes, não os substitui.' }], referencias: ['CC Art. 1.829'], fonte: 'mock' },
  { id: 24, disciplina: 'Direito Penal', topico: 'Erro de tipo', subtopico: 'Erro de fato', dificuldade: 'Difícil', banca: 'CEBRASPE', ano: 2023, enunciado: 'O erro essencial de fato exclui:', alternativas: ['A pena', 'O dolo', 'A culpa do crime', 'A responsabilidade civil'], correta: 1, explicacao: 'Erro essencial de fato exclui o dolo, permanecendo responsabilidade culposa se a lei admitir.', errosComuns: [{ alternativa: 0, motivo: 'Erro essencial de fato não exclui pena por crime culposo.' }], referencias: ['CP Art. 20', 'CP Art. 18'], fonte: 'mock' },
  { id: 25, disciplina: 'Direito Constitucional', topico: 'Ministério Público', subtopico: 'Funções constitucionais', dificuldade: 'Fácil', banca: 'FGV', ano: 2023, enunciado: 'O Ministério Público tem como função essencial:', alternativas: ['Legislar sobre tributos', 'A defesa da ordem jurídica e do regime democrático', 'Administrar a arrecadação de impostos', 'Julgar crimes contra servidores públicos'], correta: 1, explicacao: 'É função essencial do MP defender a ordem jurídica e o regime democrático, conforme CF/88 Art. 127.', errosComuns: [{ alternativa: 0, motivo: 'Legislação é função do Poder Legislativo.' }], referencias: ['CF/88 Art. 127', 'CF/88 Art. 129'], fonte: 'mock' },
  { id: 26, disciplina: 'Direito Administrativo', topico: 'Improbidade Administrativa', subtopico: 'Atos de improbidade', dificuldade: 'Média', banca: 'CEBRASPE', ano: 2022, enunciado: 'Ato de improbidade que causa enriquecimento ilícito resulta em:', alternativas: ['Perda do cargo e inabilitação', 'Multa apenas', 'Advertência escrita', 'Suspensão temporária'], correta: 0, explicacao: 'Enriquecimento ilícito resulta em perda do cargo, inabilitação e devolução de bens, conforme Lei 8.429/92.', errosComuns: [{ alternativa: 1, motivo: 'As sanções por improbidade são mais severas que multa simples.' }], referencias: ['Lei 8.429/92 Art. 9º'], fonte: 'mock' },
  { id: 27, disciplina: 'Direito Civil', topico: 'Pessoa Jurídica', subtopico: 'Constituição e natureza', dificuldade: 'Fácil', banca: 'FGV', ano: 2022, enunciado: 'A pessoa jurídica de direito público externo é representada por:', alternativas: ['Sociedades comerciais', 'Estados soberanos', 'Associações civis', 'Sindicatos'], correta: 1, explicacao: 'Estados soberanos e organismos internacionais são pessoas jurídicas de direito público externo.', errosComuns: [{ alternativa: 2, motivo: 'Associações são pessoas jurídicas de direito privado.' }], referencias: ['CC Art. 40', 'CC Art. 41'], fonte: 'mock' },
  { id: 28, disciplina: 'Direito Penal', topico: 'Concurso de crimes', subtopico: 'Concurso material', dificuldade: 'Média', banca: 'FGV', ano: 2023, enunciado: 'No concurso material de crimes, as penas são:', alternativas: ['Somadas integralmente', 'Unificadas em uma só', 'Reduzidas em 1/3', 'Aplicadas isoladamente com somação parcial'], correta: 0, explicacao: 'No concurso material, as penas são somadas integralmente, conforme CP Art. 69.', errosComuns: [{ alternativa: 1, motivo: 'Unificação de penas é para crime continuado, não material.' }], referencias: ['CP Art. 69', 'CP Art. 70'], fonte: 'mock' },
  { id: 29, disciplina: 'Direito Constitucional', topico: 'Poder Judiciário', subtopico: 'Estrutura e competência', dificuldade: 'Média', banca: 'CEBRASPE', ano: 2023, enunciado: 'O Supremo Tribunal Federal é competente para julgar originariamente:', alternativas: ['Crimes comuns de qualquer cidadão', 'Ações entre Estados-membros', 'Processos civis de pessoas físicas', 'Crimes comuns de juízes de primeira instância'], correta: 1, explicacao: 'STF julga originariamente ações entre Estados-membros, conforme CF/88 Art. 102, I, f.', errosComuns: [{ alternativa: 0, motivo: 'Crimes comuns não são competência originária do STF.' }], referencias: ['CF/88 Art. 102, I'], fonte: 'mock' },
  { id: 30, disciplina: 'Direito Civil', topico: 'Bens', subtopico: 'Classificação dos bens', dificuldade: 'Fácil', banca: 'CEBRASPE', ano: 2022, enunciado: 'Bem imóvel é aquele que:', alternativas: ['Pode ser transportado facilmente', 'Incorporado ao solo ou que não pode ser removido', 'De pequeno valor econômico', 'Sujeito a depreciação acelerada'], correta: 1, explicacao: 'Bem imóvel é aquele por natureza incorporado ao solo ou que não pode ser removido, conforme CC Art. 79.', errosComuns: [{ alternativa: 0, motivo: 'Capacidade de transporte distingue bem móvel de imóvel.' }], referencias: ['CC Art. 79', 'CC Art. 82'], fonte: 'mock' },
];

export const SIMULADOS = [
  { id: 1, nome: 'Simulado OAB - 1ª Fase Completo', questoes: 80, tempo: '5h', status: 'disponivel', ultimaNota: null },
  { id: 2, nome: 'Simulado Direito Constitucional', questoes: 20, tempo: '1h 30m', status: 'em_andamento', progresso: 45 },
  { id: 3, nome: 'Simulado Direito Civil e Processual', questoes: 20, tempo: '1h 30m', status: 'concluido', ultimaNota: 72 },
  { id: 4, nome: 'Simulado Ético-Profissional', questoes: 15, tempo: '1h', status: 'concluido', ultimaNota: 88 },
];

export const CRONOGRAMA_DIAS = [
  { dow: 'SEG', dia: 13, disciplina: 'Direito Constitucional', topico: 'Direitos e Garantias Fundamentais', tempo: '2h de estudo', qtd: '30 questões', hoje: true, progresso: 60 },
  { dow: 'TER', dia: 14, disciplina: 'Direito Administrativo', topico: 'Atos Administrativos', tempo: '2h de estudo', qtd: '25 questões', hoje: false, progresso: 0 },
  { dow: 'QUA', dia: 15, disciplina: 'Direito Penal', topico: 'Princípios do Direito Penal', tempo: '2h de estudo', qtd: '30 questões', hoje: false, progresso: 0 },
  { dow: 'QUA', dia: 16, disciplina: 'Direito Civil', topico: 'Parte Geral — Pessoas Naturais', tempo: '2h de estudo', qtd: '25 questões', hoje: false, progresso: 0 },
  { dow: 'SEX', dia: 17, disciplina: 'Direito do Trabalho', topico: 'Relação de Trabalho', tempo: '2h de estudo', qtd: '20 questões', hoje: false, progresso: 0 },
  { dow: 'SAB', dia: 18, disciplina: 'Direito Empresarial', topico: 'Empresário e Sociedade Empresária', tempo: '2h de estudo', qtd: '25 questões', hoje: false, progresso: 0 },
  { dow: 'DOM', dia: 19, disciplina: 'Revisões e Questões', topico: 'Revisão geral da semana', tempo: '2h de estudo', qtd: '40 questões', hoje: false, progresso: 0 },
];

export const ANOTACOES_FOLDERS = ['Todas', 'Direito Constitucional', 'Direito Administrativo', 'Direito Penal', 'Direito Civil', 'Direito do Trabalho'];

export const ANOTACOES = [
  { id: 1, titulo: 'Princípios da Administração Pública', disciplina: 'Direito Administrativo', tag: 'Resumo', data: 'Hoje às 10:30', conteudo: 'Os princípios da Administração Pública são diretrizes que orientam a atuação do Estado: Legalidade, Impessoalidade, Moralidade, Publicidade e Eficiência (LIMPE).' },
  { id: 2, titulo: 'Controle de Constitucionalidade', disciplina: 'Direito Constitucional', tag: 'Resumo', data: 'Ontem às 22:15', conteudo: 'O controle pode ser difuso (qualquer juiz) ou concentrado (STF), preventivo ou repressivo, exercido pelos Poderes Legislativo, Executivo e Judiciário.' },
  { id: 3, titulo: 'Prazos Processuais', disciplina: 'Direito Civil', tag: 'Mapa mental', data: '12/05/2025', conteudo: 'Mapa mental relacionando prazos processuais cíveis: contestação (15 dias úteis), recursos (15 dias úteis), embargos de declaração (5 dias úteis).' },
  { id: 4, titulo: 'Crimes contra a Administração Pública', disciplina: 'Direito Penal', tag: 'Resumo', data: '12/05/2025', conteudo: 'Peculato, corrupção passiva e ativa, concussão, prevaricação — todos exigem sujeito ativo funcionário público, com exceções específicas de cada tipo.' },
  { id: 5, titulo: 'Improbidade Administrativa (Lei 8.429/92)', disciplina: 'Direito Administrativo', tag: 'Lei seca', data: '11/05/2025', conteudo: 'A lei classifica os atos de improbidade em três categorias: que causam enriquecimento ilícito, prejuízo ao erário, e que violam princípios da administração.' },
  { id: 6, titulo: 'Responsabilidade Civil', disciplina: 'Direito Civil', tag: 'Resumo', data: '10/05/2025', conteudo: 'A responsabilidade civil pode ser subjetiva (exige culpa) ou objetiva (independe de culpa, baseada no risco da atividade).' },
];

export const DAY_ICON_MAP = {
  'Direito Constitucional': 'scale',
  'Direito Administrativo': 'clipboard-list',
  'Direito Penal': 'gavel',
  'Direito Civil': 'book-open',
  'Direito do Trabalho': 'briefcase',
  'Direito Empresarial': 'building-2',
  'Revisões e Questões': 'repeat',
};

export const TAG_COLORS = {
  'Resumo': ['#EDE9FE', null], // fg resolved to theme.primaryDark at render time
  'Mapa mental': ['#FCE7F3', '#BE185D'],
  'Lei seca': ['#FEF3C7', '#B45309'],
};

export function topicosPorDisciplina(nome) {
  const seed = nome.length;
  return ['Fundamentos', 'Princípios gerais', 'Procedimentos', 'Jurisprudência aplicada', 'Casos práticos'].map((t, i) => ({
    nome: t, pct: Math.max(20, (seed * 7 + i * 13) % 100),
  }));
}
